version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DB_URL=${DB_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GEMINI_KEY=${GEMINI_KEY}
      - DIGITAL_OCEAN_PASSWORD=${DIGITAL_OCEAN_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  node_modules: